---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Ensure directories are 0755
  command: find /var/www/ -type d -exec chmod 0755 {} \;

- name: Ensure files are 0644
  command: find /var/www/ -type f -exec chmod 0644 {} \;


- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/

- name: Creates the index.php file
  template: src=index.php.j2 dest=/var/www/html/index.php
